# Copyright 2013 Andrey Sitnik <andrey@sitnik.ru>,
# sponsored by Evil Martians.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

https = require('https')
path  = require('path')
fs    = require('fs')

module.exports =

  # Load file from Can I Use repository and run `callback` with JSON content.
  caniuse: (file, callback) ->
    https.get 'https://raw.github.com/Fyrd/caniuse/master/data.json', (res) ->
      data = '';
      res.on 'data', (chunk) -> data += chunk
      res.on 'end', -> callback(JSON.parse(data))

  # Save autogenerated `file` wirh warning comment and node.js exports.
  save: (file, json) ->
    file     = path.join(__dirname, '../../data', file)
    content  = "// Don't edit this files, because it's autogenerated.\n" +
               "// See updaters/ dir for generator. " +
                  "Run bin/update to update.\n\n"
    content += "module.exports = " + JSON.stringify(json, null, 4) + ';'
    content  = content.replace(/"([^"]+)":/g, '$1:')
    fs.writeFileSync(file, content)
