# Don't edit this files, because it's autogenerated.
# See updaters/ dir for generator. Run bin/update to update.

module.exports =
  android:
    prefix: "-webkit-"
    minor: true
    versions: [
      4.2
      4.1
      4
      3
      2.3
      2.2
      2.1
    ]
    popularity: [
      0.385341
      2.01563
      1.33387
      0.00592833
      1.96228
      0.148208
      0.0711399
    ]

  bb:
    prefix: "-webkit-"
    minor: true
    versions: [
      10
      7
    ]
    popularity: [
      0
      0.14265
    ]

  chrome:
    prefix: "-webkit-"
    future: [
      31
      30
    ]
    versions: [
      29
      28
      27
      26
      25
      24
      23
      22
      21
      20
      19
      18
      17
      16
      15
      14
      13
      12
      11
      10
      9
      8
      7
      6
      5
      4
    ]
    popularity: [
      6.7568
      22.9846
      0.7872
      0.5658
      0.4428
      0.3198
      0.2788
      0.2706
      0.5248
      0.082
      0.082
      0.1394
      0.082
      0.0984
      0.123
      0.1066
      0.1066
      0.1148
      0.164
      0.0902
      0.0246
      0.0328
      0.0246
      0.0328
      0.0246
      0.0246
    ]

  ff:
    prefix: "-moz-"
    future: [
      25
      24
    ]
    versions: [
      23
      22
      21
      20
      19
      18
      17
      16
      15
      14
      13
      12
      11
      10
      9
      8
      7
      6
      5
      4
      3.6
      3.5
      3
      2
    ]
    popularity: [
      6.1582
      6.068
      0.3772
      0.2296
      0.1886
      0.1558
      0.2214
      0.328
      0.1804
      0.123
      0.1312
      0.2378
      0.1148
      0.1312
      0.0738
      0.0738
      0.0492
      0.0492
      0.0574
      0.082
      0.287
      0.0492
      0.0902
      0.0246
    ]

  ie:
    prefix: "-ms-"
    future: [
      11
    ]
    versions: [
      10
      9
      8
      7
      6
      5.5
    ]
    popularity: [
      9.459
      4.33746
      6.89823
      0.39204
      0.191849
      0.009298
    ]

  ios:
    prefix: "-webkit-"
    versions: [
      7
      6
      6.1
      5
      5.1
      4.2
      4.3
      4
      4.1
      3.2
    ]
    popularity: [
      0
      3.477105
      3.477105
      0.306353
      0.306353
      0.04595295
      0.04595295
      0.0076588
      0.0076588
      0.00765882
    ]

  opera:
    prefix: "-o-"
    future: [
      17
    ]
    versions: [
      16
      15
      12.1
      12
      11.6
      11.5
      11.1
      11
      10.6
      10.5
      10
      10.1
      9.5
      9.6
    ]
    popularity: [
      0.0246
      0.1394
      0.5494
      0.0574
      0.0328
      0.0164
      0.0082
      0.0082
      0.0082
      0.008392
      0.0123
      0.0123
      0.0041
      0.0041
    ]

  safari:
    prefix: "-webkit-"
    future: [
      7
    ]
    versions: [
      6
      5.1
      5
      4
      3.2
      3.1
    ]
    popularity: [
      2.0008
      1.2874
      0.328
      0.0984
      0.008692
      0
    ]

;
